-  hosts: teste
   gather_facts: false
   tasks: 
    - name: Install all critical and security updates
      win_updates:
        category_names:
        - CriticalUpdates
        - SecurityUpdates
        state: installed
      register: update_result
    - name: Reboot host if required
      win_reboot:
        msg: "Esta máquina foi atualizada pelo NUTIC-PB e será reiniicada em 2 minutos ..."
        pre_reboot_delay: 120
      when: update_result.reboot_required
